[node]
url = "https://rpc.quai.network/cyprus1/"

[database]
# dsn = "postgresql://postgres:1234@localhost:5432/quai?connect_timeout=100&sslmode=disable&TimeZone=UTC"
dsn = "postgresql://postgres:Force.01@192.168.200.51:5432/quai?connect_timeout=100&sslmode=disable&TimeZone=UTC"
log_level = "silent"
# options: silent, error, warn, info

[sync]
batch_size = 10
debug_mode = false
is_from_config = false
start_height = 100
